### ISSUE TITLE
configure remediation point

### ISSUE THREAD

**Issue by amitrai4code** [ivantsepp/codeclimate-scss-lint#11]
Is there a way to configure remediation point for a specific repo.

**Comment by ivantsepp** [comment]
There is not a way to configure the remediation point as it's hardcoded https://github.com/ivantsepp/codeclimate-scss-lint/blob/15455b5049fe65249e4b72f1541bd081b463f634/lib/scss_lint/reporters/codeclimate_reporter.rb#L12. I'm wondering what the use case is and how remediation points are used?

**Comment by amitrai4code** [comment]
We have a repo with lots of style issues (in 1000s) however, because of the current value of remediation point our GPA is 3.91 which looks weird.

**Comment by ivantsepp** [comment]
Ah I see. and sorry for the delayed response. I'm more than happy to accept a PR to make this change!
