### ISSUE TITLE
Support Sass syntax linting

### ISSUE THREAD

**Issue by dahliacreative** [ivantsepp/codeclimate-scss-lint#12]
Hi, my team uses the Sass indentation syntax, I was just wondering if you could add support for that?

**Comment by ivantsepp** [comment]
Hm, sorry i missed this. But the underlying gem we use is `scss-lint` which does not provide support for sass styles. You can try https://github.com/gilbarbara/codeclimate-stylelint which is supported by CodeClimate or https://github.com/alxndr/codeclimate-sasslint which I'm not sure is released yet.

**Comment by wopian** [comment]
@ivantsepp  unfortunately `codeclimate-stylelint` doesn't support Sass, as its based on PostCSS which doesn't support it and `codeclimate-sasslint` remains unofficial and unavailable to use on codeclimate.

[sass-lint](https://www.npmjs.com/package/sass-lint) is quite mature now and lints both SCSS and Sass in JavaScript - which is probably the way to go as its not long until the ruby `scss-lint` gem becomes unmaintained.

**Comment by ivantsepp** [comment]
I agree that sass-lint is the way to go since it seems like ruby `sass` and even ruby `scss-lint` could go unmaintained/deprecated. I would propose that we push to get https://github.com/alxndr/codeclimate-sasslint official since it looks like there's some good work already done!
