### ISSUE TITLE
scss-lint gem is out of date

### ISSUE THREAD

**Issue by bholtbholt** [ivantsepp/codeclimate-scss-lint#14]
Hi, I would like to update the scss-lint gem to `0.52.0` from `0.47.1`. I've made a PR but am unable to publish it for review.

**Comment by ivantsepp** [comment]
Bumped to latest version in https://github.com/ivantsepp/codeclimate-scss-lint/commit/f5af490f3ea90de80934df39198f63c80e0c9474

@wfleming Could we get the latest code uploaded to Code Climate's docker repository?

**Comment by ivantsepp** [comment]
Latest `codeclimate-scss-lint` has been released!
