### ISSUE TITLE
Inclusion files are not honoured

### ISSUE THREAD

**Issue by bholtbholt** [ivantsepp/codeclimate-scss-lint#15]
I think this is a bug, but it could be missing documentation.

In my `scss-lint.yml` file I had `scss_files: app/assets/stylesheets/` as the only directory to include, but when Code Climate ran, it includes all directories. This caused 4000+ failures in files in `public/stylesheets/`, which I didn't want to lint.

To get around it, I explicitly added that directory (and several others) to the exclude paths.

**Bug:** The directories I've included are not being honoured. Instead, they are scanning all directories.

**Comment by ivantsepp** [comment]
Thanks for your report, we are not honoring `scss-lint`'s option for `scss_files`. Going to attempt a patch or if you have a better PR let me know!
